### ISSUE TITLE
根据您提供的信息写了一个简单的油猴脚本

### ISSUE THREAD

**Issue by TIANLI0** [Vanda688/Using-GPT4-image-recognition-on-NewBing#2]
链接：https://greasyfork.org/zh-CN/scripts/471001-bing-ai-%E5%9B%BE%E5%83%8F%E6%8B%93%E5%B1%95

**Comment by imvanda** [comment]
👍

**Comment by imvanda** [comment]
已添加到README.md, 感谢贡献
